### PR TITLE
Adjusted display offset

### PR DESCRIPTION
**Pull request by Zoli06**
There was an empty line on the side of the screen so I copied the offset values from the M5Cardputer-UserDemo

### CODE REVIEW

**Comment by syurazo** [comment]
Thanks for the pull request.

Do you have an image of the display as it appeared when you identified the problem, and as it will appear after the fix, that I can compare?

**Comment by Zoli06** [comment]
Yeah sure
Before:
before
before2
After:
after

**Comment by syurazo** [comment]
Thanks for testing.

However, when I apply the patch offset to (40,52), there is an area on the bottom line that is not drawn as shown below.

This is a problem I noticed myself when I implemented the patch with (40,52) before. So I finally adjusted it to the current offset.

apply the patch

```rust
    let mut display = display::build(
        peripherals.spi2,
        peripherals.pins.gpio36,
        peripherals.pins.gpio35,
        peripherals.pins.gpio37,
        peripherals.pins.gpio34,
        peripherals.pins.gpio33,
    )
    .unwrap();

    let bg = PrimitiveStyleBuilder::new()
        .stroke_color(Rgb565::new(16, 4, 4))
        .stroke_width(1)
        .fill_color(Rgb565::BLACK)
        .build();
    Rectangle::new(Point::new(0, 0), Size::new(240, 135))
        .into_styled(bg)
        .draw(&mut display)
        .unwrap();
```

**Comment by Zoli06** [comment]
Ah I see. I played around with the values a little bit and for me (40, 53) works the best.

**Comment by syurazo** [comment]
For 240x135, it appears that the offset should be centered at 320x240.

Horizontal offset value :  (320-240)/2=40

Vertical offset value : (240-135)/2 = 52 or 53

When scanning from bottom to top in Landscape, the offset is 52, but when scanning from top to bottom, the offset is 53. It looks like the correct offset for `Landscape(true)` is (40,53).

Can you fixup the PR with this value?

**Comment by Zoli06** [comment]
Done

**Pull request merged**
